import { TabWidget } from "std-widgets.slint";
import { Create } from "create.slint";
import { SlintRustBridge } from "slint-rust-bridge.slint";
import { Dashboard } from "dashboard.slint";
import { Execute } from "execute.slint";

export component App inherits Window {
    default-font-size: 20px;
    default-font-family: "monospace";
    title: "ruroco";
    preferred-height: 1200px;
    preferred-width: 540px;

    TabWidget {
        x: root.safe-area-insets.left;
        y: root.safe-area-insets.top;
        width: root.width - root.safe-area-insets.right - root.safe-area-insets.left;
        height: root.height - root.safe-area-insets.bottom - root.safe-area-insets.top;

        Tab {
            title: "Dashboard";
            Dashboard { }
        }

        Tab {
            title: "Create";
            Create { }
        }

        Tab {
            title: "Execute";
            Execute { }
        }
    }
}

export { SlintRustBridge }